### ISSUE TITLE
针对API的一些建议

### ISSUE THREAD

**Issue by tiannian** [RecursiveG/UniSkinServer#10]
是否可以添加对图片获取的验证和鉴权流程。而且个人现在的API设计并不完善，应该同时提供站点登录，上传，注册等现在在网页上的功能也规范成RESTful服务，这样可能更方便基于这个标准进行开发。

**Comment by RecursiveG** [comment]
UniSkinAPI只定义了一个皮肤站应该提供那些接口以便于Mod获得皮肤信息。
这些接口都是公开的并且是只读的，不必（也不能）要求鉴权。
至于服务端和网页界面之间的接口，由各个具体实现定义，不是UniSkinAPI所需要解决的问题。
