### ISSUE TITLE
Server 端上的一些提议

### ISSUE THREAD

**Issue by 17** [RecursiveG/UniSkinServer#2]
**使用 Cookie**
刷新就要重新登录了.. 

**添加 requirements.txt**
方便不懂 python 的同学直接安装依赖模块.

~~**前后端分离**
服务端提供 `RESTful` 风格的 API 的接口, 方便前端设计和处理数据.~~

~~**数据库**
现在的结构, 性能应该不错. 为了以后的扩展, 我觉得 `user` 应和 `textures` 分开.
现在的 `PlayID` 和用户名是同一个, 以后可能还需要一个 `userID` 和 `PlayID` 的对应表.~~

**Comment by Ahrwing** [comment]
他的意思是分出用户名和MCID~

**Comment by RecursiveG** [comment]
`requirements.txt`已经在这个commit里加入了 dcd02fe1ed9f54ba82a0e939b53d56ef10772381
不考虑使用 Cookie
分离账户和MCID的话，也暂时不考虑。。。~~其实是这个人懒~~
