### ISSUE TITLE
Something new?

### ISSUE THREAD

**Issue by MisterFixx** [RecursiveG/UniSkinServer#6]
I would really want to use this for my project, is there anything new with the PHP part of this repo?

**Comment by wfjsw** [comment]
PHP part failed with the first integration test, so i have abandoned it. You may use python+nginx.

**Comment by MisterFixx** [comment]
I'm not very familiar with python and i'd rather use a language i know, i would be very happy if you could keep your work on the PHP part, thanks for the update.

**Comment by RecursiveG** [comment]
@wfjsw I've simplified the API definition. Could you continue your PHP implementation?

**Comment by wfjsw** [comment]
I will try it. But the f**king things is 中考。。。。。

**Comment by MisterFixx** [comment]
Thank you guys for the effort, i really appriciate it.

**Comment by RecursiveG** [comment]
Here is a PHP alternative to UniSkinServer
https://github.com/printempw/blessing-skin-server/tree/en-US
I personally have no more interest to maintain a PHP port.
