### ISSUE TITLE
texture 文件位置问题

### ISSUE THREAD

**Issue by printempw** [RecursiveG/UniSkinServer#9]
作者的 python 实现中，是可以自定义 texture 的存储位置的（文件名为hash），但是在 tornado 中只有 /textures 的 handler，并且是 staticFileHandler。而上传的文件又是存储于自定义的 path 中。
看了一下 mod 的源码，
’’’
private static final String URL_PROFILE_FMT="{root}/{player_name}.json";
private static final String URL_TEXTURE_FMT="{root}/textures/{texture_hash}";
’’’
/textures 是写死的，是窝哪里理解错了吗？

**Comment by Ahrwing** [comment]
@@ 感覺是半成品的樣子……

**Comment by RecursiveG** [comment]
唔.....配置里的`texture-folder`暂时没用......

**Comment by RecursiveG** [comment]
现在staticFileHandler应该可以正确处理自定义文件目录了
